# Generated by Django 3.2 on 2020-06-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RelatedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('many', models.ManyToManyField(related_name='lol2', to='test_app.MyModel')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lol', to='test_app.mymodel')),
            ],
        ),
        migrations.AddIndex(
            model_name='mymodel',
            index=models.Index(fields=['id'], name='test_app_my_id_fe9bc7_idx'),
        ),
        migrations.AddIndex(
            model_name='relatedmodel',
            index=models.Index(fields=['thing'], name='test_app_re_thing_i_cedf63_idx'),
        ),
    ]
