# Generated by Django 3.2 on 2020-06-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
